services:
  postgresql:
    image: postgres:latest
    container_name: postgres-hause-services
    ports:
      - '5432:5432'
    env_file:
      - '.env'
    volumes:
      - ./data:/var/lib/postgresql/data
